//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.micen.suppliers.activity.broadcast;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.focustech.common.widget.pulltorefresh.PullToRefreshListView;
import com.micen.suppliers.R.id;
import com.micen.suppliers.view.PageStatusView;
import com.micen.suppliers.view.SearchListProgressBar;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class BroadCastActivity_
    extends BroadCastActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String BROAD_CAST_TYPE_EXTRA = "broadCastType";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static BroadCastActivity_.IntentBuilder_ intent(Context context) {
        return new BroadCastActivity_.IntentBuilder_(context);
    }

    public static BroadCastActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new BroadCastActivity_.IntentBuilder_(fragment);
    }

    public static BroadCastActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new BroadCastActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btnFunction1 = ((ImageView) hasViews.findViewById(id.common_title_function1));
        tvTitle = ((TextView) hasViews.findViewById(id.common_title_name));
        btnFunction4 = ((ImageView) hasViews.findViewById(id.common_title_function4));
        btnBack = ((ImageView) hasViews.findViewById(id.common_title_back));
        llBack = ((LinearLayout) hasViews.findViewById(id.common_ll_title_back));
        btnFunction3 = ((ImageView) hasViews.findViewById(id.common_title_function3));
        btnFunction5 = ((ImageView) hasViews.findViewById(id.common_title_function5));
        btnFunction2 = ((ImageView) hasViews.findViewById(id.common_title_function2));
        btnTextFunction = ((TextView) hasViews.findViewById(id.common_title_text_function));
        statusView = ((PageStatusView) hasViews.findViewById(id.broadcast_page_status));
        pullToRefreshListView = ((PullToRefreshListView) hasViews.findViewById(id.broadcast_listview));
        progressBar = ((SearchListProgressBar) hasViews.findViewById(id.progress_bar));
        initView();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(BROAD_CAST_TYPE_EXTRA)) {
                broadCastType = extras_.getString(BROAD_CAST_TYPE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<BroadCastActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, BroadCastActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), BroadCastActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), BroadCastActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                        fragment_.startActivityForResult(intent, requestCode, lastOptions);
                    } else {
                        fragment_.startActivityForResult(intent, requestCode);
                    }
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                            context.startActivity(intent, lastOptions);
                        } else {
                            context.startActivity(intent);
                        }
                    }
                }
            }
        }

        public BroadCastActivity_.IntentBuilder_ broadCastType(String broadCastType) {
            return super.extra(BROAD_CAST_TYPE_EXTRA, broadCastType);
        }

    }

}
