//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.micen.suppliers.view.home;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.micen.suppliers.R.layout;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class BroadcastFragment_
    extends com.micen.suppliers.view.home.BroadcastFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.broadcast_fragment_layout, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static BroadcastFragment_.FragmentBuilder_ builder() {
        return new BroadcastFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        inquiryBroadcastUnread = ((TextView) hasViews.findViewById(com.micen.suppliers.R.id.tv_inquiry_unread));
        purchaseBroadcastUnread = ((TextView) hasViews.findViewById(com.micen.suppliers.R.id.tv_purchase_unread));
        purchaseBroadcast = ((RelativeLayout) hasViews.findViewById(com.micen.suppliers.R.id.rl_broadcast_purchase));
        serviceBroadcast = ((RelativeLayout) hasViews.findViewById(com.micen.suppliers.R.id.rl_broadcast_service));
        inquiryBroadcast = ((RelativeLayout) hasViews.findViewById(com.micen.suppliers.R.id.rl_broadcast_inquiry));
        serviceBroadcastUnread = ((TextView) hasViews.findViewById(com.micen.suppliers.R.id.tv_service_unread));
        tvTitle = ((TextView) hasViews.findViewById(com.micen.suppliers.R.id.broadcast_title_name));
        initView();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<BroadcastFragment_.FragmentBuilder_, com.micen.suppliers.view.home.BroadcastFragment>
    {


        @Override
        public com.micen.suppliers.view.home.BroadcastFragment build() {
            BroadcastFragment_ fragment_ = new BroadcastFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
